# Generated by Django 5.0.2 on 2024-02-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructions',
            old_name='recepies',
            new_name='recipes',
        ),
    ]
