# Generated by Django 5.0.2 on 2024-02-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_rename_recepies_instructions_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='recipes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructions',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Recipes/'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='preparation_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='recipes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe_category',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
