# Generated by Django 5.0.2 on 2024-02-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_ingredients_recipes_instructions_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipe_category'),
        ),
        migrations.AddField(
            model_name='instructions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipe_category'),
        ),
    ]
