# Generated by Django 5.0.2 on 2024-02-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_ingredients_category_instructions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='Recipes.recipes'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='Recipes.recipes'),
        ),
    ]
