# Generated by Django 5.0.2 on 2024-02-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0005_alter_ingredients_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='category',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='instructions',
            old_name='category',
            new_name='recipe',
        ),
    ]
